 CREATE INDEX app_settings_app_provision_id_idx ON public.app_settings USING btree (app_provision_id)
 CREATE INDEX assets_space_id_asset_folder_id_created_at_idx ON public.assets USING btree (space_id, asset_folder_id, created_at) WHERE (deleted_at IS NULL)
 CREATE INDEX assets_space_id_asset_folder_id_idx ON public.assets USING btree (space_id, asset_folder_id) WHERE (deleted_at IS NULL)
 CREATE INDEX assets_space_id_content_length_created_at_idx ON public.assets USING btree (space_id, content_length, created_at) WHERE (deleted_at IS NULL)
 CREATE INDEX assets_space_id_created_at_idx ON public.assets USING btree (space_id, created_at) WHERE (deleted_at IS NULL)
 CREATE INDEX component_groups_space_id_idx1 ON public.component_groups USING btree (space_id)
 CREATE INDEX datasource_entry_children_space_id_dimension_id_idx ON public.datasource_entry_children USING btree (space_id, dimension_id)
 CREATE INDEX discussions_space_id_idea_id_idx ON public.discussions USING btree (space_id, idea_id)
 CREATE INDEX discussions_space_id_story_id_idx ON public.discussions USING btree (space_id, story_id)
 CREATE INDEX field_types_app_id_idx1 ON public.field_types USING btree (app_id)
 CREATE INDEX field_types_app_id_idx ON public.field_types USING btree (app_id)
 CREATE INDEX field_types_spaces_field_type_id_idx1 ON public.field_types_spaces USING btree (field_type_id)
 CREATE INDEX field_types_spaces_space_id_idx ON public.field_types_spaces USING btree (space_id)
 CREATE INDEX idx_taggies_partial_1 ON public.taggies USING btree (space_id) WHERE (on_deleted_story = false)
 CREATE INDEX index_api_keys_on_space_id ON public.api_keys USING btree (space_id)
 CREATE INDEX index_api_keys_stories_on_api_key_id ON public.api_keys_stories USING btree (api_key_id)
 CREATE INDEX index_api_keys_stories_on_story_id ON public.api_keys_stories USING btree (story_id)
 CREATE INDEX index_api_logs_on_space_id ON public.api_logs USING btree (space_id)
 CREATE INDEX index_app_categories_apps_on_app_category_id ON public.app_categories_apps USING btree (app_category_id)
 CREATE INDEX index_app_categories_apps_on_app_id ON public.app_categories_apps USING btree (app_id)
 CREATE INDEX index_apps_on_partner_id ON public.apps USING btree (partner_id)
 CREATE INDEX index_app_sync_connection_logs_combined ON public.app_sync_connection_logs USING btree (space_id, app_sync_connection_id, status, kind, executed_at)
 CREATE INDEX index_asset_folder_permissions_on_asset_folder_id ON public.asset_folder_permissions USING btree (asset_folder_id)
 CREATE INDEX index_asset_folder_permissions_on_space_role_id ON public.asset_folder_permissions USING btree (space_role_id)
 CREATE INDEX index_asset_folders_on_space_id ON public.asset_folders USING btree (space_id)
 CREATE INDEX index_assets_on_space_id ON public.assets USING btree (space_id)
 CREATE INDEX index_background_tasks_on_space_id ON public.background_tasks USING btree (space_id)
 CREATE INDEX index_branches_space_roles_on_branch_id ON public.branches_space_roles USING btree (branch_id)
 CREATE INDEX index_branches_space_roles_on_space_role_id ON public.branches_space_roles USING btree (space_role_id)
 CREATE INDEX index_collaborators_on_space_id ON public.collaborators USING btree (space_id)
 CREATE INDEX index_collaborators_on_user_id ON public.collaborators USING btree (user_id)
 CREATE INDEX index_collaborators_space_roles_on_collaborator_id ON public.collaborators_space_roles USING btree (collaborator_id)
 CREATE INDEX index_collaborators_space_roles_on_space_role_id ON public.collaborators_space_roles USING btree (space_role_id)
 CREATE INDEX index_comments_on_discussion_id ON public.comments USING btree (discussion_id)
 CREATE INDEX index_comments_on_idea_id ON public.comments USING btree (idea_id)
 CREATE INDEX index_comments_on_space_id_and_users_to_notify_ids ON public.comments USING gin (space_id, users_to_notify_ids)
 CREATE INDEX index_comments_on_space_id ON public.comments USING btree (space_id)
 CREATE INDEX index_comments_on_story_id ON public.comments USING btree (story_id)
 CREATE INDEX index_components_on_internal_tag_ids ON public.components USING gin (space_id, internal_tag_ids)
 CREATE INDEX index_components_on_space_id ON public.components USING btree (space_id)
 CREATE INDEX index_components_space_roles_on_component_id ON public.components_space_roles USING btree (component_id)
 CREATE INDEX index_components_space_roles_on_space_role_id ON public.components_space_roles USING btree (space_role_id)
 CREATE INDEX index_datasource_entries_on_datasource_id ON public.datasource_entries USING btree (datasource_id)
 CREATE INDEX index_datasource_entries_on_space_id ON public.datasource_entries USING btree (space_id)
 CREATE INDEX index_datasources_on_space_id ON public.datasources USING btree (space_id)
 CREATE INDEX index_datasources_space_roles_on_datasource_id ON public.datasources_space_roles USING btree (datasource_id)
 CREATE INDEX index_datasources_space_roles_on_space_role_id ON public.datasources_space_roles USING btree (space_role_id)
 CREATE INDEX index_disclaimers_on_feature_id_and_version ON public.disclaimers USING btree (feature_id, version) WHERE (active IS TRUE)
 CREATE INDEX index_discussions_on_space_id ON public.discussions USING btree (space_id)
 CREATE INDEX index_discussions_on_story_id ON public.discussions USING btree (story_id)
 CREATE INDEX index_field_types_on_org_id ON public.field_types USING btree (org_id)
 CREATE INDEX index_field_types_on_partner_id ON public.field_types USING btree (partner_id)
 CREATE INDEX index_field_types_on_user_id ON public.field_types USING btree (user_id)
 CREATE INDEX index_ideas_on_internal_tag_ids ON public.ideas USING gin (space_id, internal_tag_ids)
 CREATE INDEX index_ideas_on_space_id ON public.ideas USING btree (space_id)
 CREATE INDEX index_image_invalidations_on_asset_id ON public.image_invalidations USING btree (asset_id)
 CREATE INDEX index_image_invalidations_on_space_id ON public.image_invalidations USING btree (space_id)
 CREATE INDEX index_internal_tags_on_space_id ON public.internal_tags USING btree (space_id)
 CREATE INDEX index_invitations_on_collaborator_id ON public.invitations USING btree (collaborator_id)
 CREATE INDEX index_invitations_on_org_id ON public.invitations USING btree (org_id)
 CREATE INDEX index_invitations_on_partner_id ON public.invitations USING btree (partner_id)
 CREATE INDEX index_invitations_on_user_id ON public.invitations USING btree (user_id)
 CREATE INDEX index_leads_on_partner_id ON public.leads USING btree (partner_id)
 CREATE INDEX index_preset_filters_on_space_id ON public.preset_filters USING btree (space_id)
 CREATE INDEX index_preset_filter_users_on_preset_filter_id ON public.preset_filter_users USING btree (preset_filter_id)
 CREATE INDEX index_preset_filter_users_on_user_id ON public.preset_filter_users USING btree (user_id)
 CREATE INDEX index_presets_on_space_id ON public.presets USING btree (space_id)
 CREATE INDEX index_scheduled_contents_on_space_id ON public.scheduled_contents USING btree (space_id)
 CREATE INDEX index_settings_on_space_id ON public.settings USING btree (space_id)
 CREATE INDEX index_space_roles_stories_on_space_role_id ON public.space_roles_stories USING btree (space_role_id)
 CREATE INDEX index_space_roles_stories_on_story_id ON public.space_roles_stories USING btree (story_id)
 CREATE INDEX index_space_roles_workflow_stages_on_space_role_id ON public.space_roles_workflow_stages USING btree (space_role_id)
 CREATE INDEX index_space_roles_workflow_stages_on_workflow_stage_id ON public.space_roles_workflow_stages USING btree (workflow_stage_id)
 CREATE INDEX index_spaces_on_org_id ON public.spaces USING btree (org_id)
 CREATE INDEX index_spaces_on_parent_id ON public.spaces USING btree (parent_id)
 CREATE INDEX index_stories_ideas_on_idea_id ON public.stories_ideas USING btree (idea_id)
 CREATE INDEX index_stories_ideas_on_story_id ON public.stories_ideas USING btree (story_id)
 CREATE INDEX index_story_contents_on_space_id ON public.story_contents USING btree (space_id)
 CREATE INDEX index_story_contents_on_story_id ON public.story_contents USING btree (story_id)
 CREATE INDEX index_story_schedulings_on_space_id ON public.story_schedulings USING btree (space_id)
 CREATE INDEX index_taggies_on_space_id ON public.taggies USING btree (space_id)
 CREATE INDEX index_taggies_on_story_id ON public.taggies USING btree (story_id)
 CREATE INDEX index_taggings_on_taggable_id_and_taggable_type_and_context ON public.taggings USING btree (taggable_id, taggable_type, context)
 CREATE INDEX index_templates_on_space_id ON public.templates USING btree (space_id)
 CREATE INDEX index_traffic_boosts_on_invoice_id ON public.traffic_boosts USING btree (invoice_id)
 CREATE INDEX index_traffic_boosts_on_space_id ON public.traffic_boosts USING btree (space_id)
 CREATE INDEX index_translated_slugs_on_space_id ON public.translated_slugs USING btree (space_id)
 CREATE INDEX index_translated_slugs_on_story_id ON public.translated_slugs USING btree (story_id)
 CREATE INDEX index_translated_stories_on_space_id ON public.translated_stories USING btree (space_id)
 CREATE INDEX index_translated_stories_on_story_id ON public.translated_stories USING btree (story_id)
 CREATE INDEX index_users_on_org_id ON public.users USING btree (org_id)
 CREATE INDEX index_users_stories_on_story_id ON public.users_stories USING btree (story_id)
 CREATE INDEX index_users_stories_on_user_id ON public.users_stories USING btree (user_id)
 CREATE INDEX index_users_workflow_stages_on_user_id ON public.users_workflow_stages USING btree (user_id)
 CREATE INDEX index_users_workflow_stages_on_workflow_stage_id ON public.users_workflow_stages USING btree (workflow_stage_id)
 CREATE INDEX index_webhook_endpoints_on_space_id ON public.webhook_endpoints USING btree (space_id)
 CREATE INDEX index_webhook_logs_on_space_id ON public.webhook_logs USING btree (space_id)
 CREATE INDEX index_workflows_on_space_id_and_content_types ON public.workflows USING gin (space_id, content_types)
 CREATE INDEX index_workflows_on_space_id ON public.workflows USING btree (space_id)
 CREATE INDEX index_workflow_stage_changes_on_space_id ON public.workflow_stage_changes USING btree (space_id)
 CREATE INDEX index_workflow_stage_changes_on_story_id ON public.workflow_stage_changes USING btree (story_id)
 CREATE INDEX index_workflow_stage_changes_on_workflow_stage_id ON public.workflow_stage_changes USING btree (workflow_stage_id)
 CREATE INDEX index_workflow_stages_on_space_id ON public.workflow_stages USING btree (space_id)
 CREATE INDEX internal_tags_space_id_id_idx ON public.internal_tags USING btree (space_id, id)
 CREATE INDEX limit_boosts_space_id_created_at_idx ON public.limit_boosts USING btree (space_id, created_at DESC)
 CREATE INDEX scheduled_contents_space_id_story_id_idx ON public.scheduled_contents USING btree (space_id, story_id)
 CREATE INDEX scheduled_contents_story_id_release_id_idx ON public.scheduled_contents USING btree (story_id, release_id)
 CREATE INDEX spaces_owner_id_idx ON public.spaces USING btree (owner_id)
 CREATE INDEX stories_customer_crunchyroll_1_on_content_gin ON public.stories USING gin (((content ->> 'component'::text)), space_id) WHERE ((space_id = 235083) AND (deleted_at IS NULL))
 CREATE INDEX stories_customer_crunchyroll_on_content_gin ON public.stories USING gin (((content ->> 'component'::text)), space_id) WHERE ((space_id = 178900) AND (deleted_at IS NULL))
 CREATE INDEX stories_customer_jollyes_on_content_gin ON public.stories USING gin (content, space_id) WHERE ((space_id = 152022) AND (deleted_at IS NULL))
 CREATE INDEX stories_customer_space_252177_on_content_gin ON public.stories USING gin (((content ->> 'component'::text)), space_id) WHERE ((space_id = 252177) AND (deleted_at IS NULL))
 CREATE INDEX stories_idx_parent_id ON public.stories USING btree (parent_id)
 CREATE INDEX stories_idx_space_id_slug_include ON public.stories USING btree (space_id, slug, id) INCLUDE (is_folder, branch_id) WITH (fillfactor='70') WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_branch_id_idx ON public.stories USING btree (space_id, branch_id) WHERE ((deleted_at IS NULL) AND is_folder)
 CREATE INDEX stories_space_id_content_idx ON public.stories USING gin (space_id, content jsonb_path_ops) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_deleted_at ON public.stories USING btree (space_id, deleted_at)
 CREATE INDEX stories_space_id_group_id_branch_id_idx ON public.stories USING btree (space_id, group_id, branch_id) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_group_id_idx ON public.stories USING btree (space_id, group_id) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_idx ON public.stories USING btree (space_id) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_parent_id_idx ON public.stories USING btree (space_id, parent_id) WHERE ((deleted_at IS NULL) AND (branch_id IS NULL))
 CREATE INDEX stories_space_id_pinned_idx ON public.stories USING btree (space_id, pinned) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_position_idx ON public.stories USING btree (space_id, "position") WHERE ((deleted_at IS NULL) AND (branch_id IS NULL))
 CREATE INDEX stories_space_id_published_content_idx ON public.stories USING gin (space_id, published_content jsonb_path_ops) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_slug_idx ON public.stories USING btree (space_id, slug varchar_pattern_ops) WHERE (deleted_at IS NULL)
 CREATE INDEX stories_space_id_uuid_idx ON public.stories USING btree (space_id, uuid) WHERE (deleted_at IS NULL)
 CREATE INDEX taggies_space_id_name_idx ON public.taggies USING btree (space_id, story_id, name)
 CREATE INDEX taggies_space_id_story_id_name_idx ON public.taggies USING gin (space_id, story_id, name gin_trgm_ops)
 CREATE INDEX taggies_story_id_name_idx ON public.taggies USING btree (story_id, name)
 CREATE INDEX translated_slugs_space_id_story_id_idx ON public.translated_slugs USING btree (space_id, story_id)
 CREATE INDEX translated_stories_space_id_lang_idx ON public.translated_stories USING btree (space_id, lang)
 CREATE INDEX translated_stories_space_id_lang_published_content_idx ON public.translated_stories USING gin (space_id, lang, published_content)
 CREATE INDEX users_stories_user_id_story_id_idx ON public.users_stories USING btree (user_id, story_id)
 CREATE INDEX workflows_space_id_is_default_idx ON public.workflows USING btree (space_id, is_default)
 CREATE INDEX workflow_stages_workflow_id_idx ON public.workflow_stages USING btree (workflow_id)
 CREATE UNIQUE INDEX app_settings_app_provision_id_client_id_key ON public.app_settings USING btree (app_provision_id, client_id)
 CREATE UNIQUE INDEX comments_space_id_uuid_uq ON public.comments USING btree (space_id, uuid)
 CREATE UNIQUE INDEX discussions_space_id_uuid_uq ON public.discussions USING btree (space_id, uuid)
 CREATE UNIQUE INDEX index_app_provisions_on_space_id_and_app_id ON public.app_provisions USING btree (space_id, app_id)
 CREATE UNIQUE INDEX index_app_sync_connections_unique ON public.app_sync_connections USING btree (space_id, app_sync_instance_id, name)
 CREATE UNIQUE INDEX index_app_sync_instances_on_space_id_and_app_name ON public.app_sync_instances USING btree (space_id, app_name)
 CREATE UNIQUE INDEX index_disclaimers_on_feature_id_and_key_and_version ON public.disclaimers USING btree (feature_id, key, version)
 CREATE UNIQUE INDEX index_feature_limits_unique_on_feature_id_and_object ON public.feature_limits USING btree (feature_id, object_id, object_type)
 CREATE UNIQUE INDEX index_settings_on_setting_key_and_space_id ON public.settings USING btree (setting_key, space_id)
 CREATE UNIQUE INDEX index_users_disclaimers_on_user_id_and_disclaimer_id ON public.users_disclaimers USING btree (user_id, disclaimer_id)
 CREATE UNIQUE INDEX stories_ideas_story_id_idea_id_key ON public.stories_ideas USING btree (story_id, idea_id)
 CREATE UNIQUE INDEX taggings_idx ON public.taggings USING btree (tag_id, taggable_id, taggable_type, context, tagger_id, tagger_type)
 CREATE UNIQUE INDEX translated_slugs_story_id_lang_idx ON public.translated_slugs USING btree (story_id, lang)
 CREATE UNIQUE INDEX translated_stories_story_id_lang_key ON public.translated_stories USING btree (story_id, lang)
 CREATE UNIQUE INDEX uq_id_space_id ON public.datasources USING btree (id, space_id)

